### this is the architectural mind behind the system. tf will not pay if they agree to test it and and that upon successful pilot i can reference them in my documents ehen a potential client asks for proof of efficiency.


Jusclick-TeQiQ 
Product Proposal
1. The Problem
In many organizations, visitor access is still controlled through a simple manual process.
A visitor arrives at the gate and says they are expected to meet someone. The security officer contacts the named host to confirm the visit. If the host confirms that they are expecting someone matching the visitor's description, the visitor is allowed to enter and records their details in a visitor logbook.
The process appears reasonable, but it leaves several important gaps.
First is the identity and authorization gap.
A host confirming that they are expecting a visitor does not establish that the person standing at the gate is actually the person the host intended to meet. The procedure confirms an expectation; it does not provide a controlled credential that can be verified at the point of entry.
Second is the operational dependency on the host.
The security officer must often wait for someone who may be in a meeting, away from the office, or simply unable to respond immediately. This creates unnecessary waiting at the gate, interrupts employees, and can turn a routine arrival into a prolonged manual verification process.
Third is the handling of visitor information.
Traditional paper visitor books can contain names, telephone numbers, organizations, persons visited, departments, visit purposes, arrival and departure times, vehicle information and other personal information. A visitor completing today's entry may be able to see information recorded by visitors who arrived before them.
That creates an avoidable confidentiality and personal-data exposure.
2. Security, Operational and Data-Protection Risk
These weaknesses are not merely matters of convenience.
From a security perspective, the organization is relying heavily on a verbal confirmation process rather than a controlled pre-authorization and verification mechanism.
Operationally, the gate becomes dependent on telephone communication and the availability of individual employees.
From a data-protection perspective, organizations handling personal information are expected to manage that information appropriately, including considerations around access, security, transparency, retention and disclosure. Ghana's Data Protection Act, 2012 (Act 843) establishes requirements governing the processing and protection of personal data and provides for offences and penalties for certain non-compliance.
This does not mean that every paper visitor book automatically constitutes a legal violation, nor does Jusclick-TeQiQ  by itself make an organization legally compliant. Rather, the existing procedure should be assessed against the organization's obligations and the actual way visitor information is collected, exposed, retained and accessed.
The objective is therefore not simply to replace paper with software. It is to remove specific weaknesses in the access-control process while giving the organization better control over the information generated by that process.
3. The Jusclick-TeQiQ  Approach
Jusclick-TeQiQ  is a controlled visitor and temporary-access system designed around that specific problem.
Instead of waiting for an unverified visitor to arrive and then beginning the authorization process at the gate, the visit can be authorized before arrival.
The basic workflow is:
Authorized staff → Visitor assignment → Temporary credential → Gate verification → Access record
An authorized user creates the visit and provides the relevant information, such as the visitor's identity, host, department, purpose and, where applicable, company, appointment details or other operational information.
Jusclick-TeQiQ  then issues a temporary three-word passcode associated with that assignment.
The visitor presents the passcode at the gate.
The security officer validates it through the Jusclick-TeQiQ  gate terminal. The system can determine whether the credential is valid and whether the corresponding assignment is available for entry.
The resulting access activity is recorded as part of the organization's security record.
This changes the fundamental question at the gate from:
"Can someone confirm that a visitor like this is expected?"
to:
"Is there an active, authorized visit matching the credential being presented?"
4. What Jusclick-TeQiQ  Controls
Jusclick-TeQiQ  supports the operational categories that commonly pass through a controlled entrance, including:
•	Visitors
•	Contractors
•	Suppliers and deliveries
The assignment process can capture the information necessary for the particular category and establish the conditions under which the temporary access credential is valid.
Security personnel then work from the system's verification result rather than relying entirely on telephone conversations, handwritten entries or informal descriptions.
The system also provides structured records of access activity, creating a clearer operational trail than a paper book alone.
5. An Important Security Boundary
Jusclick-TeQiQ 's temporary passcode is a credential, not proof of a person's physical identity.
Possession of a valid passcode demonstrates that the person presenting it has the issued credential. It does not, by itself, prove that the person is the individual originally intended to receive access.
Where an organization requires stronger identity assurance, Jusclick-TeQiQ  can operate alongside additional controls such as government-issued identification, employee/host confirmation, photographs, escort requirements, CCTV verification or restricted-area procedures.
This distinction is important because effective access control should not confuse credential verification with identity verification.
6. Operational Effect
Jusclick-TeQiQ  is intended to address the practical bottlenecks created by the existing process.
A visitor can be authorized before reaching the gate. Security personnel can verify the issued credential directly. The host does not necessarily need to interrupt a meeting simply to confirm that an expected visitor has arrived.
The result is a more controlled process with less dependence on:
•	Repeated telephone calls
•	Availability of individual hosts
•	Handwritten records
•	Verbal descriptions
•	Manual searching through previous visitor entries
The system also gives management and authorized personnel a structured view of access activity rather than leaving the organization's visitor history entirely in a physical register.
7. Data Protection Considerations
Jusclick-TeQiQ  is designed to reduce unnecessary exposure of visitor information at the point of entry.
Instead of requiring every visitor to interact with a shared book containing historical visitor records, access information is handled through the system and presented according to the user's authorized operational role.
However, the organization remains responsible for determining appropriate data-retention periods, lawful processing purposes, internal access rules, privacy notices and other requirements applicable to its operations.
Jusclick-TeQiQ  provides security and access-control mechanisms; it does not replace the organization's responsibility to establish and maintain its own data-protection policies and compliance processes.
8. Proposed Client Evaluation
Jusclick-TeQiQ  can be introduced through a controlled pilot at one entrance, reception point or selected operational area.
The evaluation should use real operational scenarios, including:
•	A normal pre-authorized visitor
•	A contractor
•	A supplier or delivery
•	An invalid credential
•	An expired or cancelled visit
•	A visitor arriving outside the expected conditions
•	A host who is unavailable
•	Entry and departure recording
•	Security personnel operating the gate without relying on the paper visitor book
The purpose of the pilot is not simply to demonstrate that the software works.
It is to determine whether Jusclick-TeQiQ  addresses the organization's actual security and operational weaknesses, whether the workflow is practical for security personnel and staff, and what additional controls may be required for the organization's particular risk environment.
9. Commercial Value
For an organization, the value of Jusclick-TeQiQ  is measured in control rather than features.
It provides a mechanism for:
•	Pre-authorizing access rather than beginning authorization after arrival.
•	Verifying temporary credentials at the point of entry.
•	Reducing dependence on host availability for routine visitor verification.
•	Reducing gate delays and unnecessary interruptions.
•	Improving control over visitor information.
•	Maintaining structured access records.
•	Creating greater accountability around who authorized and processed access.
Jusclick-TeQiQ  is therefore intended to become part of the organization's access-control procedure—not simply another visitor register.
Conclusion
The underlying problem is straightforward: the traditional process often establishes that someone is expected, but provides limited assurance that the person at the gate is presenting a controlled authorization to enter.
Jusclick-TeQiQ  introduces that missing control layer by moving authorization before arrival and verification to the point of entry, while providing a structured record of the resulting access activity.
The proposed next step is a controlled client pilot in which the existing procedure and Jusclick-TeQiQ  are tested against real visitor scenarios, security requirements, operational constraints and data-protection considerations.
BRIGHT ANDERSON
Jusclick-TeQiQ  — Controlled Access. Verified Entry. Accountable Operations.


