import React, { useMemo, useState } from "react";
import {
  BookOpen,
  Check,
  CheckCircle2,
  FileText,
  Lock,
  Printer,
  Search,
  ShieldAlert,
  ShieldCheck,
  X,
} from "lucide-react";
import {
  CURRENT_POLICY_VERSION,
  hasUserAcceptedPolicy,
  recordPolicyAcceptance,
  togglePilotScenarioCheck,
  useGateRegistry,
} from "../lib/gateRegistry";

export const JUSCLICK_PROPOSAL_SECTIONS = [
  {
    num: "1",
    title: "The Problem",
    summary: "Identity & authorization gap, operational dependency on hosts, and paper logbook PII exposure.",
    paragraphs: [
      "In many organizations, visitor access is still controlled through a simple manual process. A visitor arrives at the gate and says they are expected to meet someone. The security officer contacts the named host to confirm the visit. If the host confirms that they are expecting someone matching the visitor's description, the visitor is allowed to enter and records their details in a visitor logbook.",
      "The process appears reasonable, but it leaves several important gaps:",
    ],
    bullets: [
      "First — The Identity & Authorization Gap: A host confirming that they are expecting a visitor does not establish that the person standing at the gate is actually the person the host intended to meet. The procedure confirms an expectation; it does not provide a controlled credential that can be verified at the point of entry.",
      "Second — Operational Dependency on the Host: The security officer must often wait for someone who may be in a meeting, away from the office, or simply unable to respond immediately. This creates unnecessary waiting at the gate, interrupts employees, and can turn a routine arrival into a prolonged manual verification process.",
      "Third — Handling of Visitor Information: Traditional paper visitor books can contain names, telephone numbers, organizations, persons visited, departments, visit purposes, arrival and departure times, vehicle information and other personal information. A visitor completing today's entry may be able to see information recorded by visitors who arrived before them — creating an avoidable confidentiality and personal-data exposure.",
    ],
  },
  {
    num: "2",
    title: "Security, Operational and Data-Protection Risk",
    summary: "Verbal confirmation risk, gate bottlenecks, and Ghana's Data Protection Act, 2012 (Act 843).",
    paragraphs: [
      "These weaknesses are not merely matters of convenience. From a security perspective, the organization is relying heavily on a verbal confirmation process rather than a controlled pre-authorization and verification mechanism. Operationally, the gate becomes dependent on telephone communication and the availability of individual employees.",
      "From a data-protection perspective, organizations handling personal information are expected to manage that information appropriately, including considerations around access, security, transparency, retention and disclosure. Ghana's Data Protection Act, 2012 (Act 843) establishes requirements governing the processing and protection of personal data and provides for offences and penalties for certain non-compliance.",
      "This does not mean that every paper visitor book automatically constitutes a legal violation, nor does Jusclick-TeQiQ by itself make an organization legally compliant. Rather, the existing procedure should be assessed against the organization's obligations and the actual way visitor information is collected, exposed, retained and accessed.",
      "The objective is therefore not simply to replace paper with software. It is to remove specific weaknesses in the access-control process while giving the organization better control over the information generated by that process.",
    ],
    bullets: [],
  },
  {
    num: "3",
    title: "The Jusclick-TeQiQ Approach",
    summary: "Authorized staff → Visitor assignment → Temporary credential → Gate verification → Access record.",
    paragraphs: [
      "Jusclick-TeQiQ is a controlled visitor and temporary-access system designed around that specific problem. Instead of waiting for an unverified visitor to arrive and then beginning the authorization process at the gate, the visit can be authorized before arrival.",
      "The basic workflow is: Authorized staff → Visitor assignment → Temporary credential → Gate verification → Access record.",
      "An authorized user creates the visit and provides the relevant information, such as the visitor's identity, host, department, purpose and, where applicable, company, appointment details or other operational information. The system then issues a temporary passcode associated with that assignment.",
      "The visitor presents the passcode at the gate. The security officer validates it through the gate terminal. The system determines whether the credential is valid and whether the corresponding assignment is available for entry, recording the resulting access activity as part of the organization's security record.",
    ],
    bullets: [
      'Changes the fundamental question at the gate from: "Can someone confirm that a visitor like this is expected?"',
      'To: "Is there an active, authorized visit matching the credential being presented?"',
    ],
  },
  {
    num: "4",
    title: "What Jusclick-TeQiQ Controls",
    summary: "Structured assignment and verification for Visitors, Contractors, and Suppliers & Deliveries.",
    paragraphs: [
      "Jusclick-TeQiQ supports the operational categories that commonly pass through a controlled entrance. The assignment process captures the information necessary for the particular category and establishes the conditions under which the temporary access credential is valid.",
      "Security personnel then work from the system's verification result rather than relying entirely on telephone conversations, handwritten entries or informal descriptions. The system also provides structured records of access activity, creating a clearer operational trail than a paper book alone.",
    ],
    bullets: [
      "Visitors — Pre-scheduled guests, clients, and regulatory or corporate visitors.",
      "Contractors — Maintenance, engineering, and third-party technical personnel.",
      "Suppliers and Deliveries — Logistics, raw material deliveries, and dispatch operators.",
    ],
  },
  {
    num: "5",
    title: "An Important Security Boundary",
    summary: "Distinguishing credential verification from physical identity verification at the gate.",
    paragraphs: [
      "A temporary passcode is a credential, not proof of a person's physical identity. Possession of a valid passcode demonstrates that the person presenting it has the issued credential. It does not, by itself, prove that the person is the individual originally intended to receive access.",
      "Where an organization requires stronger identity assurance, Jusclick-TeQiQ operates alongside additional controls such as government-issued identification (Ghana Card, Passport, Voter ID, Driver's License), employee/host confirmation, photographs, escort requirements, CCTV verification or restricted-area procedures.",
      "This distinction is critical because effective access control should never confuse credential verification with identity verification.",
    ],
    bullets: [],
  },
  {
    num: "6",
    title: "Operational Effect",
    summary: "Removing gate delays, host interruptions, and manual register dependencies.",
    paragraphs: [
      "Jusclick-TeQiQ is intended to address the practical bottlenecks created by the existing process. A visitor can be authorized before reaching the gate. Security personnel can verify the issued credential directly. The host does not necessarily need to interrupt a meeting simply to confirm that an expected visitor has arrived.",
      "The system also gives management and authorized personnel a structured view of access activity rather than leaving the organization's visitor history entirely in a physical register.",
    ],
    bullets: [
      "Less dependence on repeated telephone calls at the gate",
      "Less dependence on immediate availability of individual hosts",
      "Elimination of exposed handwritten visitor records",
      "Elimination of informal verbal descriptions",
      "Elimination of manual searching through previous visitor entries",
    ],
  },
  {
    num: "7",
    title: "Data Protection Considerations",
    summary: "Role-scoped access control and organizational compliance responsibilities under Act 843.",
    paragraphs: [
      "Jusclick-TeQiQ is designed to reduce unnecessary exposure of visitor information at the point of entry. Instead of requiring every visitor to interact with a shared book containing historical visitor records, access information is handled through the system and presented strictly according to the user's authorized operational role.",
      "However, the organization remains responsible for determining appropriate data-retention periods, lawful processing purposes, internal access rules, privacy notices and other requirements applicable to its operations.",
      "Jusclick-TeQiQ provides security and access-control mechanisms; it does not replace the organization's responsibility to establish and maintain its own data-protection policies and compliance processes.",
    ],
    bullets: [],
  },
  {
    num: "8",
    title: "Proposed Client Evaluation (Controlled Pilot)",
    summary: "Real-world operational scenarios for testing at TF Commodities.",
    paragraphs: [
      "Jusclick-TeQiQ can be introduced through a controlled pilot at one entrance, reception point or selected operational area.",
      "The purpose of the pilot is not simply to demonstrate that the software works. It is to determine whether Jusclick-TeQiQ addresses the organization's actual security and operational weaknesses, whether the workflow is practical for security personnel and staff, and what additional controls may be required for the organization's particular risk environment.",
    ],
    bullets: [
      "A normal pre-authorized visitor",
      "A contractor",
      "A supplier or delivery",
      "An invalid credential",
      "An expired or cancelled visit",
      "A visitor arriving outside the expected conditions",
      "A host who is unavailable",
      "Entry and departure (check-in & check-out) recording",
      "Security personnel operating the gate without relying on the paper visitor book",
    ],
  },
  {
    num: "9",
    title: "Commercial Value & Conclusion",
    summary: "Measured in operational control, verified entry, and accountable security records.",
    paragraphs: [
      "For an organization, the value of Jusclick-TeQiQ is measured in control rather than features. Jusclick-TeQiQ is intended to become part of the organization's access-control procedure—not simply another visitor register.",
      "Conclusion: The underlying problem is straightforward: the traditional process often establishes that someone is expected, but provides limited assurance that the person at the gate is presenting a controlled authorization to enter. Jusclick-TeQiQ introduces that missing control layer by moving authorization before arrival and verification to the point of entry, while providing a structured record of the resulting access activity.",
      "BRIGHT ANDERSON — Jusclick-TeQiQ: Controlled Access. Verified Entry. Accountable Operations.",
    ],
    bullets: [
      "Pre-authorizing access rather than beginning authorization after arrival",
      "Verifying temporary credentials at the point of entry",
      "Reducing dependence on host availability for routine visitor verification",
      "Reducing gate delays and unnecessary interruptions",
      "Improving control over visitor information",
      "Maintaining structured access records",
      "Creating greater accountability around who authorized and processed access",
    ],
  },
];

export const DATA_PROTECTION_POLICY_CLAUSES = [
  {
    code: "DP-01",
    title: "Personal Data Protection & Confidentiality (Ghana Data Protection Act, 2012 — Act 843)",
    body: "All visitor, contractor, and supplier records—including full names, telephone numbers, national ID numbers, vehicle registration plates, companies, host assignments, and entry/departure timestamps—constitute protected personal data. Users must only collect, view, or process visitor data strictly for authorized operational and physical security purposes.",
  },
  {
    code: "DP-02",
    title: "Role-Based Access Control (RBAC) & Zero-BOLA Enforcement",
    body: "Access to system records is strictly scoped by role and department. Staff members may only view passcodes and visitors they individually issued; Department Heads may only view records belonging to their bound department; Security Admins manage gate verification and authorized operational exports; System Admins govern user approvals, system configuration, and the immutable System Audit Log.",
  },
  {
    code: "DP-03",
    title: "Credential Verification vs. Physical Identity Verification Boundary",
    body: "A temporary passcode is a pre-authorization credential, NOT standalone proof of physical identity. Security personnel operating the gate terminal must verify the visitor's physical government-issued identification (e.g., Ghana Card, Passport, Driver's License) against the pre-authorized visitor details before granting on-site check-in.",
  },
  {
    code: "DP-04",
    title: "Prohibition of Unauthorized Disclosure or Export",
    body: "Historical visitor records must never be exposed to other visitors or unauthorized third parties. Exporting operational rosters or audit reports is restricted strictly to authorized Security/System Administrators and must be handled in accordance with organizational data-retention policies.",
  },
  {
    code: "DP-05",
    title: "Mandatory Audit Logging & Operator Accountability",
    body: "Every action performed in this system—including policy acceptance prior to login, passcode issuance, gate validation, visitor check-in, visitor check-out, detail mismatch rejection, and administrative configuration—is permanently recorded in the Audit Ledger with your identity and timestamp.",
  },
];

export const PILOT_SCENARIOS = [
  {
    id: "S1",
    title: "1. Normal Pre-Authorized Visitor",
    expected: "Host issues single-use passcode; guard validates code at gate, verifies ID, issues badge, and checks visitor in.",
  },
  {
    id: "S2",
    title: "2. Contractor Assignment & Entry",
    expected: "Contractor passcode issued with company, department, and validity hours; verified and logged on site.",
  },
  {
    id: "S3",
    title: "3. Supplier or Delivery Clearance",
    expected: "Supplier/delivery passcode issued with vehicle registration plate and purpose; cleared and tracked at gate.",
  },
  {
    id: "S4",
    title: "4. Invalid Credential & Brute-Force Protection",
    expected: "Invalid 6-digit code is immediately denied and logged; 15 failed attempts within 10m automatically lock the gate.",
  },
  {
    id: "S5",
    title: "5. Expired or Cancelled / Revoked Visit",
    expected: "Revoked or expired passcodes are rejected at the gate terminal with a clear 'Revoked' or 'Expired' status.",
  },
  {
    id: "S6",
    title: "6. Visitor Arriving Outside Expected Conditions (Identity Mismatch)",
    expected: "Guard validates code during Stage 1 inspection but rejects entry upon discovering an ID or host mismatch.",
  },
  {
    id: "S7",
    title: "7. Host Unavailable Scenario",
    expected: "Security officer verifies pre-authorized credential directly at the gate without waiting on phone confirmation.",
  },
  {
    id: "S8",
    title: "8. Entry (Check-In) and Departure (Check-Out) Audit Recording",
    expected: "Both gate check-in (gate.checkin) and check-out (gate.checkout) are permanently recorded in the Audit Ledger and CSV reports.",
  },
  {
    id: "S9",
    title: "9. Paperless Gate Operation & Data Privacy",
    expected: "Gate operates end-to-end without a shared paper visitor book, preventing visitors from viewing prior visitors' personal data.",
  },
];

function fmtTime(ms: number) {
  return new Date(ms).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/* ==================== POLICY MODAL (PRE-LOGIN & WORKSPACE) ==================== */
export function PolicyAgreementModal({
  open,
  onClose,
  onAccept,
  userEmail,
  userName,
}: {
  open: boolean;
  onClose: () => void;
  onAccept: () => void;
  userEmail?: string;
  userName?: string;
}) {
  if (!open) return null;

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 120,
        background: "rgba(7, 11, 18, 0.78)",
        backdropFilter: "blur(6px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 16,
      }}
      role="dialog"
      aria-modal="true"
      aria-label="Data Protection and Security Policies"
    >
      <div
        className="panel"
        style={{
          width: "min(760px, 96vw)",
          maxHeight: "88dvh",
          display: "flex",
          flexDirection: "column",
          background: "var(--surface-solid)",
          border: "1px solid var(--line-strong)",
          boxShadow: "var(--shadow-pop)",
          padding: 20,
          gap: 14,
        }}
      >
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <ShieldCheck size={18} style={{ color: "var(--sig)" }} />
              <h2 style={{ fontSize: 16, fontWeight: 700, margin: 0 }}>
                Data Protection &amp; Security Operations Policy ({CURRENT_POLICY_VERSION})
              </h2>
            </div>
            <p className="status-mute" style={{ fontSize: 12, marginTop: 4 }}>
              Jusclick-TeQiQ Architecture · Aligned with Ghana&apos;s Data Protection Act, 2012 (Act 843) · Mandatory Acceptance Logged
            </p>
          </div>
          <button type="button" className="ghost-btn" onClick={onClose} style={{ minHeight: 28, padding: 4 }}>
            <X size={16} />
          </button>
        </div>

        <div
          style={{
            overflowY: "auto",
            paddingRight: 6,
            display: "flex",
            flexDirection: "column",
            gap: 10,
            borderTop: "1px solid var(--line)",
            borderBottom: "1px solid var(--line)",
            paddingTop: 12,
            paddingBottom: 12,
          }}
        >
          {DATA_PROTECTION_POLICY_CLAUSES.map(clause => (
            <div
              key={clause.code}
              style={{
                padding: "10px 12px",
                borderRadius: 6,
                background: "var(--surface-subtle)",
                border: "1px solid var(--line)",
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                <span className="mono status-ok" style={{ fontSize: 11, fontWeight: 700 }}>
                  [{clause.code}]
                </span>
                <strong style={{ fontSize: 13 }}>{clause.title}</strong>
              </div>
              <p style={{ fontSize: 12.5, color: "var(--ink-secondary)", margin: 0, lineHeight: 1.5 }}>
                {clause.body}
              </p>
            </div>
          ))}

          <div
            style={{
              padding: "10px 12px",
              borderRadius: 6,
              background: "var(--warn-bg)",
              border: "1px solid var(--warn-border)",
              fontSize: 12,
              color: "var(--ink)",
            }}
          >
            <strong>Audit Notice:</strong> Clicking <em>&ldquo;I Agree &amp; Accept Policy&rdquo;</em> logs a permanent{" "}
            <code className="mono">policy.accept</code> record in the security audit ledger{userEmail ? ` for ${userEmail}` : ""}.
          </div>
        </div>

        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, flexWrap: "wrap" }}>
          <span className="meta-inline">
            {userName || userEmail ? `Operator: ${userName || userEmail}` : "Required prior to authentication"}
          </span>
          <div style={{ display: "flex", gap: 8 }}>
            <button type="button" onClick={onClose}>
              <span>Close</span>
            </button>
            <button
              type="button"
              className="pri"
              onClick={() => {
                onAccept();
                onClose();
              }}
            >
              <Check size={14} />
              <span>I Agree &amp; Accept Policy (Logged)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ==================== WORKSPACE DOCUMENTATION MODULE ==================== */
export function Documentation({
  me,
  role,
}: {
  me: { _id: string; userId: string; name: string; email: string; role: string };
  role: string;
}) {
  const registry = useGateRegistry();
  const [subTab, setSubTab] = useState<"proposal" | "policies" | "pilot">("proposal");
  const [search, setSearch] = useState("");
  const [policyFeedback, setPolicyFeedback] = useState("");

  const isAccepted = hasUserAcceptedPolicy(me.email, me.userId);
  const myAcceptanceRecord =
    registry.policyAcceptances[me.email.toLowerCase()] ??
    registry.policyAcceptances[me.userId] ??
    registry.policyAcceptances.__latest_session__;

  const allAcceptances = useMemo(() => {
    const seen = new Set<string>();
    const list = [];
    for (const [k, rec] of Object.entries(registry.policyAcceptances)) {
      if (k === "__latest_session__") continue;
      if (seen.has(rec.email)) continue;
      seen.add(rec.email);
      list.push(rec);
    }
    return list.sort((a, b) => b.acceptedAt - a.acceptedAt);
  }, [registry.policyAcceptances]);

  const filteredProposalSections = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return JUSCLICK_PROPOSAL_SECTIONS;
    return JUSCLICK_PROPOSAL_SECTIONS.filter(
      s =>
        s.title.toLowerCase().includes(q) ||
        s.summary.toLowerCase().includes(q) ||
        s.paragraphs.some(p => p.toLowerCase().includes(q)) ||
        s.bullets.some(b => b.toLowerCase().includes(q))
    );
  }, [search]);

  const verifiedScenarioCount = PILOT_SCENARIOS.filter(
    s => registry.pilotScenarioChecks[s.id]?.verified
  ).length;

  return (
    <>
      <div className="page-header">
        <div>
          <h1>System Documentation &amp; Security Policies</h1>
          <div className="meta-inline" style={{ marginTop: 2 }}>
            Jusclick-TeQiQ Architectural Specification · Data Protection (Act 843) &amp; TF Commodities Pilot Evaluation
          </div>
        </div>

        <div className="page-header-actions no-print">
          <div className="segmented" role="group">
            <button
              type="button"
              aria-pressed={subTab === "proposal"}
              onClick={() => setSubTab("proposal")}
            >
              Architecture &amp; Proposal
            </button>
            <button
              type="button"
              aria-pressed={subTab === "policies"}
              onClick={() => setSubTab("policies")}
            >
              Data Protection &amp; Policies
            </button>
            <button
              type="button"
              aria-pressed={subTab === "pilot"}
              onClick={() => setSubTab("pilot")}
            >
              Pilot Evaluation ({verifiedScenarioCount}/{PILOT_SCENARIOS.length})
            </button>
          </div>
          <button type="button" onClick={() => window.print()}>
            <Printer size={14} />
            <span>Print Dossier</span>
          </button>
        </div>
      </div>

      {subTab === "proposal" && (
        <>
          <section className="panel">
            <div className="panel-header" style={{ flexWrap: "wrap", gap: 10 }}>
              <div>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <BookOpen size={16} style={{ color: "var(--sig)" }} />
                  <h2 className="panel-title">
                    Jusclick-TeQiQ — Controlled Access. Verified Entry. Accountable Operations.
                  </h2>
                </div>
                <p className="status-mute" style={{ fontSize: 12.5, marginTop: 4 }}>
                  Architectural Mind &amp; Product Proposal by <strong>Bright Anderson</strong> · Controlled Pilot Edition for{" "}
                  <strong>TF Commodities</strong>
                </p>
              </div>
              <div className="search-box no-print" style={{ minWidth: 240 }}>
                <Search size={14} />
                <input
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                  placeholder="Search documentation sections…"
                />
              </div>
            </div>

            <div
              style={{
                padding: "12px 14px",
                borderRadius: 8,
                background: "var(--surface-subtle)",
                border: "1px solid var(--line)",
                marginBottom: 16,
                fontSize: 12.5,
                lineHeight: 1.55,
              }}
            >
              <strong>Pilot Evaluation Context:</strong> This system is deployed for controlled client evaluation to demonstrate
              pre-authorized visitor, contractor, and supplier access control, eliminating manual paper logbook exposure and host
              telephone bottlenecks while establishing verifiable operational efficiency.
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              {filteredProposalSections.map(sec => (
                <article
                  key={sec.num}
                  className="panel"
                  style={{ background: "var(--surface-subtle)", padding: "14px 16px" }}
                >
                  <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 8, marginBottom: 6 }}>
                    <h3 style={{ fontSize: 14.5, fontWeight: 700, margin: 0 }}>
                      <span className="mono" style={{ color: "var(--sig)", marginRight: 8 }}>
                        0{sec.num}.
                      </span>
                      {sec.title}
                    </h3>
                    <span className="meta-inline">{sec.summary}</span>
                  </div>

                  <div style={{ display: "flex", flexDirection: "column", gap: 8, fontSize: 13, lineHeight: 1.6 }}>
                    {sec.paragraphs.map((p, idx) => (
                      <p key={idx} style={{ margin: 0, color: "var(--ink)" }}>
                        {p}
                      </p>
                    ))}

                    {sec.bullets.length > 0 && (
                      <ul style={{ margin: "4px 0 0", paddingLeft: 20, color: "var(--ink-secondary)" }}>
                        {sec.bullets.map((b, idx) => (
                          <li key={idx} style={{ marginBottom: 4 }}>
                            {b}
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                </article>
              ))}
            </div>
          </section>
        </>
      )}

      {subTab === "policies" && (
        <>
          <section className="panel">
            <div className="panel-header">
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <Lock size={16} style={{ color: "var(--sig)" }} />
                <h2 className="panel-title">
                  Mandatory Data Protection (Ghana Act 843) &amp; Security Operations Policy
                </h2>
              </div>
              <span className={`mono ${isAccepted ? "status-ok" : "status-warn"}`} style={{ fontSize: 12 }}>
                {isAccepted
                  ? `Accepted & Logged (${myAcceptanceRecord ? fmtTime(myAcceptanceRecord.acceptedAt) : CURRENT_POLICY_VERSION})`
                  : "Acceptance Required"}
              </span>
            </div>

            {policyFeedback && (
              <div className="gate-banner granted" role="status" style={{ marginTop: 0, marginBottom: 14 }}>
                <strong>Policy Acceptance Logged</strong>
                <p style={{ fontSize: 12.5, marginTop: 2 }}>{policyFeedback}</p>
              </div>
            )}

            <div style={{ display: "flex", flexDirection: "column", gap: 10, marginBottom: 16 }}>
              {DATA_PROTECTION_POLICY_CLAUSES.map(clause => (
                <div
                  key={clause.code}
                  className="panel"
                  style={{ background: "var(--surface-subtle)", padding: "12px 14px" }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                    <span className="mono status-ok" style={{ fontSize: 11.5, fontWeight: 700 }}>
                      [{clause.code}]
                    </span>
                    <strong style={{ fontSize: 13.5 }}>{clause.title}</strong>
                  </div>
                  <p style={{ margin: 0, fontSize: 13, lineHeight: 1.55, color: "var(--ink-secondary)" }}>
                    {clause.body}
                  </p>
                </div>
              ))}
            </div>

            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                gap: 12,
                flexWrap: "wrap",
                paddingTop: 12,
                borderTop: "1px solid var(--line)",
              }}
            >
              <div style={{ fontSize: 12.5 }}>
                <strong>Your Policy Status:</strong>{" "}
                {myAcceptanceRecord ? (
                  <span className="status-ok">
                    Agreed to {myAcceptanceRecord.policyVersion} on {fmtTime(myAcceptanceRecord.acceptedAt)}
                  </span>
                ) : (
                  <span className="status-warn">Not yet logged for this account</span>
                )}
              </div>
              <button
                type="button"
                className="pri"
                onClick={() => {
                  const rec = recordPolicyAcceptance({
                    email: me.email,
                    name: me.name,
                    userId: me.userId,
                    context: "workspace_gate",
                  });
                  setPolicyFeedback(
                    `Logged policy acceptance (${rec.policyVersion}) for ${me.name} (${me.email}) at ${fmtTime(rec.acceptedAt)}.`
                  );
                }}
              >
                <CheckCircle2 size={14} />
                <span>{isAccepted ? "Re-Affirm & Log Policy Agreement" : "Agree & Log Policy Acceptance"}</span>
              </button>
            </div>
          </section>

          {(role === "admin" || role === "security") && (
            <section className="panel">
              <div className="panel-header">
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <FileText size={16} style={{ color: "var(--sig)" }} />
                  <h2 className="panel-title">Logged User Policy Acceptances ({allAcceptances.length})</h2>
                </div>
                <span className="meta-inline">Every pre-login and workspace policy agreement is recorded</span>
              </div>

              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>User / Operator</th>
                      <th>Email</th>
                      <th>Policy Version</th>
                      <th>Acceptance Stage</th>
                      <th>Logged Timestamp</th>
                    </tr>
                  </thead>
                  <tbody>
                    {allAcceptances.length === 0 ? (
                      <tr>
                        <td colSpan={5} className="status-mute" style={{ textAlign: "center", padding: 18 }}>
                          No policy acceptances logged yet.
                        </td>
                      </tr>
                    ) : (
                      allAcceptances.map(rec => (
                        <tr key={`${rec.email}_${rec.acceptedAt}`}>
                          <td style={{ fontWeight: 600 }}>{rec.name}</td>
                          <td className="mono">{rec.email}</td>
                          <td className="mono status-ok">{rec.policyVersion}</td>
                          <td className="mono" style={{ fontSize: 12 }}>{rec.context}</td>
                          <td className="mono" style={{ fontSize: 12 }}>{fmtTime(rec.acceptedAt)}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </section>
          )}
        </>
      )}

      {subTab === "pilot" && (
        <section className="panel">
          <div className="panel-header">
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <ShieldAlert size={16} style={{ color: "var(--sig)" }} />
              <h2 className="panel-title">
                Section 8 — Controlled Client Pilot Evaluation Matrix (TF Commodities)
              </h2>
            </div>
            <span className="mono status-ok" style={{ fontSize: 12 }}>
              {verifiedScenarioCount} / {PILOT_SCENARIOS.length} Scenarios Verified
            </span>
          </div>

          <p className="status-mute" style={{ fontSize: 13, marginBottom: 14 }}>
            Use this live evaluation matrix during the TF Commodities gate pilot to verify each operational scenario
            from Section 8 of the Jusclick-TeQiQ proposal. Toggling any scenario records a{" "}
            <code className="mono">pilot.evaluate</code> entry in the System Audit Log.
          </p>

          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Scenario</th>
                  <th>Expected Operational &amp; Security Behavior</th>
                  <th>Status</th>
                  <th className="no-print" style={{ textAlign: "right" }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {PILOT_SCENARIOS.map(sc => {
                  const check = registry.pilotScenarioChecks[sc.id];
                  const verified = Boolean(check?.verified);
                  return (
                    <tr key={sc.id}>
                      <td style={{ fontWeight: 600 }}>{sc.title}</td>
                      <td style={{ color: "var(--ink-secondary)", fontSize: 12.5 }}>{sc.expected}</td>
                      <td>
                        {verified ? (
                          <div>
                            <span className="status-ok" style={{ fontWeight: 600 }}>Verified</span>
                            <div className="meta-inline mono">
                              by {check?.verifiedBy} · {check ? fmtTime(check.verifiedAt) : ""}
                            </div>
                          </div>
                        ) : (
                          <span className="status-mute">Pending Test</span>
                        )}
                      </td>
                      <td className="no-print" style={{ textAlign: "right" }}>
                        <button
                          type="button"
                          className={verified ? "" : "pri"}
                          style={{ minHeight: 28, padding: "3px 10px", fontSize: 12 }}
                          onClick={() => togglePilotScenarioCheck(sc.id, me.name)}
                        >
                          <Check size={12} />
                          <span>{verified ? "Mark Pending" : "Verify Scenario"}</span>
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </section>
      )}
    </>
  );
}
